name: Build and Push Frontend Docker Image

on:
  push:
    branches: [ "main" ]   # runs on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.kbhargav163 }}
          password: ${{ secrets.Spark@163 }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.kbhargav163 }}/quiz-frontend:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.kbhargav163 }}/quiz-frontend:latest
