name: Build, Push and Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (with backend API URL)
        run: |
               docker build \
                --build-arg NEXT_PUBLIC_API_URL=http://${{ secrets.EC2_HOST }}:8080/api \
                -t ${{ secrets.DOCKER_USERNAME }}/quiz-frontend:latest .


      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/quiz-frontend:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/quiz-deploy && sudo docker-compose pull && sudo docker-compose up -d
